print("ABC", "DEF", "XYZ")
print("ABC", "DEF", "XYZ", sep="!")
print("ABC", "DEF", "XYZ", sep="--*--")
print("ABC", "DEF", "XYZ", sep=" ")
print("ABC", "DEF", "XYZ", sep="!")
print("Hello", "Goodbye", end="@#")
